# -*- coding: utf-8 -*-
"""语音报时台词/歌词库：经典电影台词与歌词（中英文）。

纯数据模块，零依赖（不引入 Qt / edge_tts），供纯逻辑层 voice_chime.py 按日期
确定性洗牌后顺序取用（当天固定一套排列、跨天整套换新）。新增条目无需登记配置，
追加到列表即可（洗牌只看库长，不需要人工分批）。

库长即是「一天之内会不会重句」的上限：定时频率越高越要长。当前库长对最高频
的现实配置（每 15 分钟 → 96 次/天）留有余量，即一天之内不会出现同一句。
"""
from __future__ import annotations

# 中文台词/歌词：经典电影中文名句、华语歌词与短诗（尽量短，适合语音播报）。
CHINESE_QUOTES: tuple[str, ...] = (
    "生活就像一盒巧克力，你永远不知道下一颗是什么味道。",
    "曾经有一份真诚的爱情放在我面前，我没有珍惜。",
    "做人如果没有梦想，那和咸鱼有什么分别？",
    "能力越大，责任越大。",
    "明天，又是新的一天。",
    "所有的相遇，都是久别重逢。",
    "人生没有彩排，每一天都是现场直播。",
    "每一个不曾起舞的日子，都是对生命的辜负。",
    "不要放弃，永远不要放弃。",
    "山重水复疑无路，柳暗花明又一村。",
    "千里之行，始于足下。",
    "心若向阳，无畏悲伤。",
    "你若安好，便是晴天。",
    "世界那么大，我想去看看。",
    "岁月不居，时节如流。",
    "长路奉献给远方，玫瑰奉献给爱情。",
    "越过山丘，虽然已白了头。",
    "时间是让人猝不及防的东西，晴时有风阴有时雨。",
    "如果全世界我也可以放弃，至少还有你值得我去珍惜。",
    "没有什么能够阻挡，你对自由的向往。",
    "我曾经跨过山和大海，也穿过人山人海。",
    "最初的梦想，紧握在手上。",
    "想飞上天，和太阳肩并肩。",
    "我和我最后的倔强，握紧双手绝对不放。",
    "夜空中最亮的星，能否听清。",
    "海阔天空，在勇敢以后。",
    "把每天当成是末日来相爱。",
    "慢慢喜欢你，慢慢的亲密。",
    "回忆像个说书的人，用充满乡音的口吻。",
    "不要愁老之将至，你老了一定很可爱。",
    "人生天地间，忽如远行客。",
    "真正的勇气，是知道生活的真相后依然热爱生活。",
    "有些事现在不做，一辈子都不会做了。",
    "人生就像一场戏，因为有缘才相聚。",
    "你若不离不弃，我必生死相依。",
    "愿你走出半生，归来仍是少年。",
    "生活不止眼前的苟且，还有诗和远方。",
    "陪伴是最长情的告白。",
    "最好的时光，就是现在。",
    "每一次告别，都要用力一点。",
    # —— 扩库（2026-09 台词每日换新时补足，一天之内不重句）——
    "心之所向，素履以往。",
    "一万年太久，只争朝夕。",
    "面朝大海，春暖花开。",
    "人生如逆旅，我亦是行人。",
    "长风破浪会有时，直挂云帆济沧海。",
    "会当凌绝顶，一览众山小。",
    "海内存知己，天涯若比邻。",
    "行到水穷处，坐看云起时。",
    "采菊东篱下，悠然见南山。",
    "落霞与孤鹜齐飞，秋水共长天一色。",
    "人生若只如初见。",
    "当时只道是寻常。",
    "一蓑烟雨任平生。",
    "不积跬步，无以至千里。",
    "有志者，事竟成。",
    "天道酬勤。",
    "路虽远行则将至，事虽难做则必成。",
    "与其感慨路难行，不如马上出发。",
    "万物皆有裂痕，那是光照进来的地方。",
    "热爱可抵岁月漫长。",
    "生活明朗，万物可爱。",
    "人间值得，未来可期。",
    "前路浩浩荡荡，万事尽可期待。",
    "愿你三冬暖，愿你春不寒。",
    "愿你眼中有光，心中有暖。",
    "愿你被这个世界温柔以待。",
    "愿你成为自己的太阳，无需凭借谁的光。",
    "愿有岁月可回首，且以深情共白头。",
    "愿君多采撷，此物最相思。",
    "所有的幸运，都是努力埋下的伏笔。",
    "星光不问赶路人，时光不负有心人。",
    "请保持热爱，奔赴下一场山海。",
    "认真生活的人，运气都不会太差。",
    "人生没有白走的路，每一步都算数。",
    "慢慢变好，才是给自己最好的礼物。",
    "别急，你正在成为你想成为的人。",
    "慢慢来，比较快。",
    "只要还有明天，今天就永远是起跑线。",
    "把握现在，就是创造未来。",
    "世界会向那些有目标和远见的人让路。",
    "与其羡慕别人，不如点亮自己。",
    "半山腰太挤了，去山顶看看吧。",
    "你要悄悄拔尖，然后惊艳所有人。",
    "稳住，我们能赢。",
    "别慌，问题不大。",
    "认真摸鱼，好好生活。",
    "今天也要好好吃饭呀。",
    "记得喝水，记得休息。",
    "累了就休息，不用一直坚强。",
    "今天也辛苦了。",
    "记得抬头看看月亮。",
    "一切都会好起来的。",
    "你很好，你值得。",
    "允许一切发生。",
    "平安喜乐，万事顺遂。",
    "一切尽意，百事从欢。",
    "万事胜意，来日可期。",
    "愿你所愿，终能实现。",
    "心之所愿，无所不成。",
    "你若盛开，清风自来。",
    "生活原本沉闷，但跑起来就有风。",
    "山高路远，我们来日方长。",
    "风起时，正是扬帆时。",
    "岁月漫长，值得等待。",
    "人生海海，山山而川，不过尔尔。",
    "小舟从此逝，江海寄余生。",
    "天生我材必有用。",
    "欲穷千里目，更上一层楼。",
    "莫愁前路无知己，天下谁人不识君。",
    "海阔凭鱼跃，天高任鸟飞。",
    "沉舟侧畔千帆过，病树前头万木春。",
    "不畏浮云遮望眼，自缘身在最高层。",
    "问渠那得清如许，为有源头活水来。",
    "博观而约取，厚积而薄发。",
    "路漫漫其修远兮，吾将上下而求索。",
    "少年易老学难成，一寸光阴不可轻。",
    "一寸光阴一寸金。",
    "今日事，今日毕。",
    "愿你以渺小启程，以伟大结束。",
    "愿你历尽千帆，归来仍是少年。",
)

# 英文台词/歌词：经典电影台词与英文歌词（短句，适合英文音色）。
ENGLISH_QUOTES: tuple[str, ...] = (
    "Life was like a box of chocolates. You never know what you're gonna get.",
    "May the Force be with you.",
    "Carpe diem. Seize the day, boys.",
    "I'm the king of the world!",
    "Houston, we have a problem.",
    "Just keep swimming.",
    "There's no place like home.",
    "Here's looking at you, kid.",
    "I'll be back.",
    "Keep your friends close, but your enemies closer.",
    "With great power comes great responsibility.",
    "It's not who I am underneath, but what I do that defines me.",
    "Why so serious?",
    "Do, or do not. There is no try.",
    "You talking to me?",
    "Frankly, my dear, I don't give a damn.",
    "Go ahead, make my day.",
    "To be or not to be, that is the question.",
    "The stuff that dreams are made of.",
    "May you live in interesting times.",
    "Imagine all the people living life in peace.",
    "Don't stop believin'.",
    "Here comes the sun, and I say it's all right.",
    "Let it be, let it be.",
    "Yesterday, all my troubles seemed so far away.",
    "We are the champions, my friends.",
    "I will always love you.",
    "Nothing's gonna change my love for you.",
    "Every breath you take, every move you make.",
    "Sweet dreams are made of this.",
    "Wake me up when September ends.",
    "All you need is love.",
    "Let it go, let it go.",
    "I see the light.",
    "The greatest thing you'll ever learn is just to love and be loved in return.",
    "You had me at hello.",
    "Love means never having to say you're sorry.",
    "Some people are worth melting for.",
    "The sea, once it casts its spell, holds one in its net of wonder forever.",
    "Not all those who wander are lost.",
    # —— 扩库（2026-09 台词每日换新时补足，一天之内不重句）——
    "Keep your eyes on the stars and your feet on the ground.",
    "It always seems impossible until it's done.",
    "The best way to predict the future is to invent it.",
    "Whatever you are, be a good one.",
    "You miss one hundred percent of the shots you don't take.",
    "The only way to do great work is to love what you do.",
    "Stay hungry, stay foolish.",
    "Simplicity is the ultimate sophistication.",
    "What we do in life echoes in eternity.",
    "Why do we fall? So we can learn to pick ourselves up.",
    "The night is darkest just before the dawn.",
    "Everything you can imagine is real.",
    "The best is yet to come.",
    "Dream big and dare to fail.",
    "Turn your wounds into wisdom.",
    "Every day may not be good, but there's something good in every day.",
    "You are never too old to set another goal.",
    "Believe you can and you're halfway there.",
    "After all this time? Always.",
    "It does not do to dwell on dreams and forget to live.",
    "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.",
    "Not all treasure is silver and gold, mate.",
    "Roads? Where we're going we don't need roads.",
    "You're gonna need a bigger boat.",
    "Show me the money!",
    "You can't handle the truth!",
    "Elementary, my dear Watson.",
    "Hasta la vista, baby.",
    "Keep calm and carry on.",
    "Here's to the ones who dream.",
    "To infinity and beyond!",
    "Adventure is out there!",
    "All it takes is faith and trust.",
    "Second star to the right and straight on till morning.",
    "You've got a friend in me.",
    "Somewhere over the rainbow, way up high.",
    "I believe I can fly.",
    "Don't worry, be happy.",
    "What a wonderful world.",
    "Singin' in the rain.",
    "Live long and prosper.",
    "Winter is coming.",
    "Wax on, wax off.",
    "Nobody puts Baby in a corner.",
    "You shall not pass!",
    "It's alive! It's alive!",
    "E.T. phone home.",
    "The truth is out there.",
    "Space: the final frontier.",
    "Resistance is futile.",
    "I'm gonna make him an offer he can't refuse.",
    "Keep moving forward.",
    "A dream is a wish your heart makes.",
    "When you wish upon a star.",
    "Lean on me, when you're not strong.",
    "Raindrops keep fallin' on my head.",
)
